name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: data-pipeline-service
  REGION: asia-south1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Configure Docker for GCP
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      # Step 4: Debug file paths (optional)
      - name: Debug Files
        run: ls -R

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:latest -f Deployment/Dockerfile .

      # Step 6: Push Docker Image to GCR
      - name: Push Docker Image
        run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

      # Step 7: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
