name: Deploy Models to GCP

on:
  push:
    branches:
      - Test_Deployment
    paths:
      - 'Models/**'

jobs:
  deploy:
    name: Deploy Models to Google Cloud Platform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Authenticate with Google Cloud
      run: |
        echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > ${{ runner.temp }}/gcloud.json
        gcloud auth activate-service-account --key-file=${{ runner.temp }}/gcloud.json

    - name: Upload Models to Google Cloud Storage
      run: |
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
        gcloud storage cp .\Models  gs://model-storage-group-18 --recursive       
        

    - name: Deploy Models to Vertex AI
      run: |
        gcloud ai models upload \
          --region=us-central1 \
          --display-name=model-deployment \
          --artifact-uri=gs://$GCP_BUCKET_NAME/Models/
      env:
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
