name: GCP Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - Deployment/** 
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  BUCKET: ${{ secrets.GCP_BUCKET_NAME }}
  INGESTION_IMAGE_NAME: ingestion-pipeline
  PREDICTION_IMAGE_NAME: prediction-pipeline
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

       - name: Copy Models to GCS
        run: gcloud storage cp ./Models gs://capstone-model-group-18 --recursive

      # Authenticate Docker to push to GCR
      - name: Authenticate Docker
        run: gcloud auth configure-docker

      # Build and Push Ingestion Pipeline Docker Image
      - name: Build and Push Ingestion Docker Image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.INGESTION_IMAGE_NAME }}:latest -f Deployment/Dockerfile .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.INGESTION_IMAGE_NAME }}:latest

      # Build and Push Prediction Pipeline Docker Image
      - name: Build and Push Prediction Docker Image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.PREDICTION_IMAGE_NAME }}:latest -f Deployment/Dockerfile .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.PREDICTION_IMAGE_NAME }}:latest

      # Create Flex Template for Ingestion Pipeline
      - name: Create Ingestion Flex Template
        run: |
          gcloud dataflow flex-template build gs://$BUCKET/templates/ingestion_pipeline.json \
            --image gcr.io/$PROJECT_ID/$INGESTION_IMAGE_NAME:latest \
            --sdk-language "PYTHON"

      # Create Flex Template for Prediction Pipeline
      - name: Create Prediction Flex Template
        run: |
          gcloud dataflow flex-template build gs://$BUCKET/templates/prediction_pipeline.json \
            --image gcr.io/$PROJECT_ID/$PREDICTION_IMAGE_NAME:latest \
            --sdk-language "PYTHON"

      # Update or Create Cloud Scheduler for Ingestion Pipeline
      - name: Update Cloud Scheduler for Ingestion
        run: |
          gcloud scheduler jobs update http ingestion-scheduler \
            --schedule "0 * * * *" \
            --uri "https://dataflow.googleapis.com/v1b3/projects/$PROJECT_ID/locations/$REGION/flexTemplates:launch" \
            --http-method POST \
            --message-body '{
              "jobName": "hourly-ingestion",
              "parameters": {
                "project": "'$PROJECT_ID'",
                "tempLocation": "gs://'$BUCKET'/temp/",
                "region": "'$REGION'"
              },
              "environment": {
                "tempLocation": "gs://'$BUCKET'/temp/"
              }
            }' \
            --oauth-service-account-email=$SERVICE_ACCOUNT \
            --location=$REGION || gcloud scheduler jobs create http ingestion-scheduler \
            --schedule "0 * * * *" \
            --uri "https://dataflow.googleapis.com/v1b3/projects/$PROJECT_ID/locations/$REGION/flexTemplates:launch" \
            --http-method POST \
            --message-body '{
              "jobName": "hourly-ingestion",
              "parameters": {
                "project": "'$PROJECT_ID'",
                "tempLocation": "gs://'$BUCKET'/temp/",
                "region": "'$REGION'"
              },
              "environment": {
                "tempLocation": "gs://'$BUCKET'/temp/"
              }
            }' \
            --oauth-service-account-email=$SERVICE_ACCOUNT \
            --location=$REGION

      # Update or Create Cloud Scheduler for Prediction Pipeline
      - name: Update Cloud Scheduler for Prediction
        run: |
          gcloud scheduler jobs update http prediction-scheduler \
            --schedule "0 0 * * *" \
            --uri "https://dataflow.googleapis.com/v1b3/projects/$PROJECT_ID/locations/$REGION/flexTemplates:launch" \
            --http-method POST \
            --message-body '{
              "jobName": "daily-prediction",
              "parameters": {
                "project": "'$PROJECT_ID'",
                "tempLocation": "gs://'$BUCKET'/temp/",
                "region": "'$REGION'"
              },
              "environment": {
                "tempLocation": "gs://'$BUCKET'/temp/"
              }
            }' \
            --oauth-service-account-email=$SERVICE_ACCOUNT \
            --location=$REGION || gcloud scheduler jobs create http prediction-scheduler \
            --schedule "0 0 * * *" \
            --uri "https://dataflow.googleapis.com/v1b3/projects/$PROJECT_ID/locations/$REGION/flexTemplates:launch" \
            --http-method POST \
            --message-body '{
              "jobName": "daily-prediction",
              "parameters": {
                "project": "'$PROJECT_ID'",
                "tempLocation": "gs://'$BUCKET'/temp/",
                "region": "'$REGION'"
              },
              "environment": {
                "tempLocation": "gs://'$BUCKET'/temp/"
              }
            }' \
            --oauth-service-account-email=$SERVICE_ACCOUNT \
            --location=$REGION
