name: Deploy Prediction to Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Google Cloud Project ID
  REGION: asia-south1  # Cloud Run region
  SERVICE_NAME: prediction-service  # Service name
  DOCKERFILE_PATH: Deployment/Dockerfile  # Dockerfile location

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout only the Deployment directory
      - name: Checkout Deployment Directory
        uses: actions/checkout@v3
        with:
          path: Deployment  # Only checkout Deployment directory

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Configure Google Cloud SDK
      - name: Configure Google Cloud SDK
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth configure-docker gcr.io

      # Step 4: Build and Push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:latest -f Deployment/Dockerfile Deployment/
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
